using AegisErp.Domain.Entities;

namespace AegisErp.Infrastructure;

/// <summary>Starter company records used when seeding a fresh database.</summary>
public static class CompanyDefaults
{
    /// <summary>The primary demo company, carrying the full GL / AR / AP dataset.</summary>
    public static CompanySetup Aegis() => new()
    {
        LegalName = "Aegis FZE",
        TradeName = "Aegis ERP",
        CompanyCode = "AEGIS",
        LicenseNumber = "DXB-2019-104578",
        LicenseType = "FZE",
        RegistrationDate = new(2019, 6, 1),
        LicenseExpiryDate = new(2026, 5, 31),
        Country = "UAE",
        Emirate = "Dubai",
        PlaceOfIncorporation = "Dubai Airport Free Zone",
        IsFreeZone = true,
        IsDesignatedZone = true,
        FinancialYearStart = new(2025, 7, 1),
        FinancialYearEnd = new(2026, 6, 30),
        BooksStartDate = new(2025, 7, 1),
        AccountingMethod = "Accrual",
        FiscalYear = "Jul–Jun",
        BaseCurrency = "AED",
        ReportingCurrency = "AED",
        OrganizationLanguage = "English",
        CommunicationLanguage = "English, Arabic",
        InvoiceLanguage = "English",
        TimeZone = "Asia/Dubai",
        DateFormat = "dd/MM/yyyy",
        AddressLine1 = "Office 1204, Building A2",
        AddressLine2 = "Dubai Airport Free Zone",
        City = "Dubai",
        AddressEmirate = "Dubai",
        POBox = "54321",
        AddressCountry = "UAE",
        Phone = "+971 4 701 0000",
        BillingSameAsRegistered = true,
        VatRegistered = true,
        TrnLabel = "TRN",
        TrnNumber = "100123456700003",
        VatRegistrationDate = new(2018, 1, 1),
        VatScheme = "Standard",
        VatFilingFrequency = "Quarterly",
        CtRegistered = true,
        CtTrn = "100123456700003",
        FirstTaxPeriodStart = new(2025, 7, 1),
        FreeZonePerson = true,
        QfzpStatus = true,
        SmallBusinessRelief = false,
        DefaultVatRate = 5m,
        InputVatAccountCode = "13010",
        OutputVatAccountCode = "22010",
        MultiCompanyEnabled = true,
        AuditTrailEnabled = true,
        ApprovalWorkflowEnabled = false,
        BankAccounts = new()
        {
            new() { BankName = "Emirates NBD", AccountName = "Aegis FZE", AccountNumber = "1015482930001", Iban = "AE070260001015482930001", Swift = "EBILAEAD", Currency = "AED", IsPrimary = true },
            new() { BankName = "Mashreq Bank", AccountName = "Aegis FZE", AccountNumber = "019100234567", Iban = "AE930330000019100234567", Swift = "BOMLAEAD", Currency = "AED", IsPrimary = false },
        },
    };

    /// <summary>A second client company, so company switching and isolation are visible on first run.</summary>
    public static CompanySetup Meridian() => new()
    {
        LegalName = "Meridian Trading LLC",
        TradeName = "Meridian Trading",
        CompanyCode = "MERID",
        LicenseNumber = "AUH-2021-887431",
        LicenseType = "LLC",
        RegistrationDate = new(2021, 3, 15),
        LicenseExpiryDate = new(2027, 3, 14),
        Country = "UAE",
        Emirate = "Abu Dhabi",
        PlaceOfIncorporation = "Abu Dhabi",
        IsFreeZone = false,
        IsDesignatedZone = false,
        FinancialYearStart = new(2026, 1, 1),
        FinancialYearEnd = new(2026, 12, 31),
        BooksStartDate = new(2026, 1, 1),
        AccountingMethod = "Accrual",
        FiscalYear = "Jan–Dec",
        BaseCurrency = "AED",
        ReportingCurrency = "AED",
        OrganizationLanguage = "English",
        CommunicationLanguage = "English",
        InvoiceLanguage = "English",
        TimeZone = "Asia/Dubai",
        DateFormat = "dd/MM/yyyy",
        AddressLine1 = "Unit 7, Al Reem Tower",
        City = "Abu Dhabi",
        AddressEmirate = "Abu Dhabi",
        POBox = "11223",
        AddressCountry = "UAE",
        Phone = "+971 2 555 3300",
        BillingSameAsRegistered = true,
        VatRegistered = true,
        TrnLabel = "TRN",
        TrnNumber = "100998877660003",
        VatRegistrationDate = new(2021, 4, 1),
        VatScheme = "Standard",
        VatFilingFrequency = "Quarterly",
        CtRegistered = true,
        CtTrn = "100998877660003",
        FirstTaxPeriodStart = new(2026, 1, 1),
        DefaultVatRate = 5m,
        InputVatAccountCode = "13010",
        OutputVatAccountCode = "22010",
        MultiCompanyEnabled = true,
        AuditTrailEnabled = true,
        BankAccounts = new()
        {
            new() { BankName = "ADCB", AccountName = "Meridian Trading LLC", AccountNumber = "220045566778", Iban = "AE120030022004556677800", Swift = "ADCBAEAA", Currency = "AED", IsPrimary = true },
        },
    };
}
